#!/usr/bin/env bash
# ============================================================================
# Generate deploy/single/secrets.yaml from deploy/single/.env.
#
#   Same shape as deploy/k3s/make-secrets.sh, one difference: k3s can be fed
#   secrets IMPERATIVELY (kubectl create secret | apply) so nothing lands on
#   disk. `podman kube play` takes only YAML, so a file is unavoidable — it is
#   written 0600 and .gitignore'd, and it is the ONLY file in this directory
#   that holds secret material. base64 is not encryption; do not commit it.
#
#   This script also GENERATES the credentials that .env leaves blank and
#   writes them back into .env, so a first install needs nothing from the user
#   but the LLM endpoint and key. It never overwrites a value that is already
#   set — which is what makes it safe to re-run, and what protects the two
#   keys that must never change:
#     LITELLM_SALT_KEY    encrypts the stored LiteLLM virtual keys
#     N8N_ENCRYPTION_KEY  decrypts the stored Gmail OAuth credential
#
#   Usage:  ./make-secrets.sh
# ============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$HERE/.env"
OUT="$HERE/secrets.yaml"

[[ -f "$ENV_FILE" ]] || {
  echo "FATAL: $ENV_FILE not found. Start from: cp env.example .env" >&2
  exit 1
}

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

: "${CC_POD_PREFIX:=cc-}"

[[ -n "${CC_LLM_API_KEY:-}" ]] || {
  echo "FATAL: CC_LLM_API_KEY is empty in $ENV_FILE — nothing can generate it." >&2
  exit 1
}

# Set a variable in .env only if it is currently empty, generating a value.
# Idempotent by construction: a second run sees a non-empty value and leaves
# it alone, which is the entire safety story for the two never-rotate keys.
ensure() {
  local name="$1"
  if [[ -n "${!name:-}" ]]; then return; fi
  local val
  val="$(openssl rand -hex 24)"
  printf -v "$name" '%s' "$val"
  export "${name?}"
  if grep -q "^${name}=" "$ENV_FILE"; then
    # The value is hex, so no sed metacharacters can appear in it.
    sed -i "s|^${name}=.*|${name}=${val}|" "$ENV_FILE"
  else
    printf '%s=%s\n' "$name" "$val" >>"$ENV_FILE"
  fi
  echo "  generated $name"
}

echo "generating missing credentials in .env:"
ensure LITELLM_MASTER_KEY
ensure LITELLM_SALT_KEY
ensure LITELLM_POSTGRES_PASSWORD
ensure NEO4J_PASSWORD
ensure N8N_ENCRYPTION_KEY
ensure N8N_DB_PASSWORD

# Graphiti's three credentials SHOULD be LiteLLM virtual keys scoped to one
# model group each. Until the installer mints them, fall back to the master
# key: coarser, but a working install beats a broken one, and the fallback is
# visible here rather than hidden in a manifest.
: "${GRAPHITI_LLM_API_KEY:=$LITELLM_MASTER_KEY}"
: "${EMBEDDER_API_KEY:=$LITELLM_MASTER_KEY}"
: "${RERANKER_API_KEY:=$LITELLM_MASTER_KEY}"

# Embeddings may be served by a different endpoint than chat; when they are
# not, the embed alias uses the same credential. Never generated — it belongs
# to the user's endpoint.
: "${CC_EMBED_API_KEY:=$CC_LLM_API_KEY}"

: "${N8N_DB_USER:=n8n}"
: "${N8N_DB_NAME:=n8n}"

umask 077
{
  echo "# GENERATED by make-secrets.sh — DO NOT COMMIT. Regenerate, never edit."
  cat <<YAML
apiVersion: v1
kind: Secret
metadata:
  name: ${CC_POD_PREFIX}litellm
stringData:
  LITELLM_MASTER_KEY: "${LITELLM_MASTER_KEY}"
  LITELLM_SALT_KEY: "${LITELLM_SALT_KEY}"
  LITELLM_POSTGRES_PASSWORD: "${LITELLM_POSTGRES_PASSWORD}"
  DATABASE_URL: "postgresql://llmproxy:${LITELLM_POSTGRES_PASSWORD}@${CC_POD_PREFIX}litellm-db:5432/litellm"
  CC_LLM_API_KEY: "${CC_LLM_API_KEY}"
  CC_EMBED_API_KEY: "${CC_EMBED_API_KEY}"
  # Admin-UI login, optional and never generated. LiteLLM reads these with
  # os.getenv(..., None), so an EMPTY string would become the real password —
  # substitute its own defaults (admin / master key) instead, which is exactly
  # what it does when the vars are absent. The master key is in this Secret
  # already, so this adds no exposure.
  UI_USERNAME: "${UI_USERNAME:-admin}"
  UI_PASSWORD: "${UI_PASSWORD:-$LITELLM_MASTER_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CC_POD_PREFIX}neo4j
stringData:
  # NEO4J_AUTH is the container's expected "user/password" form; Graphiti
  # wants the bare password. Same source value, two shapes.
  NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"
  NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CC_POD_PREFIX}graphiti
stringData:
  GRAPHITI_LLM_API_KEY: "${GRAPHITI_LLM_API_KEY}"
  EMBEDDER_API_KEY: "${EMBEDDER_API_KEY}"
  RERANKER_API_KEY: "${RERANKER_API_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CC_POD_PREFIX}n8n
stringData:
  N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY}"
  N8N_DB_USER: "${N8N_DB_USER}"
  N8N_DB_PASSWORD: "${N8N_DB_PASSWORD}"
  N8N_DB_NAME: "${N8N_DB_NAME}"
YAML
} >"$OUT"
chmod 600 "$OUT"

echo
# chmod is a silent no-op on NTFS (2026-08-21 Windows validation, W8) — verify
# the mode actually took instead of printing an unconditional "0600".
mode="$(stat -c %a "$OUT" 2>/dev/null || echo unknown)"
if [[ "$mode" == "600" ]]; then
  echo "wrote $OUT (0600, gitignored)"
else
  echo "wrote $OUT (gitignored)"
  echo "NOTE: filesystem did not apply 0600 (Windows/NTFS) — the file relies"
  echo "on the user account's ACLs; single-user box assumed."
fi
echo "Back it up OUTSIDE this tree — LITELLM_SALT_KEY and N8N_ENCRYPTION_KEY"
echo "can never be rotated without losing what they encrypt."
