#!/usr/bin/env bash
# ============================================================================
# Render the play files from deploy/single/.env.
#
#   Dumb on purpose: envsubst plus a heredoc. There is no template engine and
#   there should not be one.
#
#   TWO THINGS THIS SCRIPT EXISTS TO GET RIGHT
#
#   1. envsubst is given an EXPLICIT variable list. Both templates contain
#      ${...} references that are NOT ours — graphiti expands ${NEO4J_PASSWORD},
#      ${EMBEDDER_API_KEY}, ${GRAPHITI_GROUP_ID:main} and friends from its own
#      container environment at startup, and LiteLLM reads `os.environ/...`.
#      A bare `envsubst` would replace those with empty strings and the graph
#      would come up with no password and no keys. Anything not in the list
#      below passes through untouched.
#
#   2. schema.sql is emitted SEPARATELY, without envsubst. It is 1000+ lines of
#      SQL containing `$` (dollar-quoted bodies), which envsubst would mangle
#      into silence. It is written as its own ConfigMap document, first, so it
#      exists before the pod that mounts it.
#
#   Usage:  ./render.sh          # writes stack-llm.yaml, models.json, stack.yaml, optional-*.yaml
#           ./render.sh llm      # ONLY stack-llm.yaml + models.json (CC_EMBED_DIM not needed yet)
#
#   The `llm` mode is what LiteLLM-first setup (2026-08-25) uses: the proxy
#   comes up before the embedding dimension has been measured, so the core
#   file — the only one that carries ${CC_EMBED_DIM} — cannot be rendered yet.
# ============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
ENV_FILE="$HERE/.env"
SCHEMA="$REPO_ROOT/central_command/db/schema.sql"

[[ -f "$ENV_FILE" ]] || { echo "FATAL: $ENV_FILE not found (cp env.example .env)" >&2; exit 1; }
[[ -f "$SCHEMA"   ]] || { echo "FATAL: $SCHEMA not found" >&2; exit 1; }

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

# Defaults, so a hand-written .env can be minimal.
: "${CC_POD_PREFIX:=cc-}"
: "${CC_PG_PORT:=5442}"
: "${CC_LITELLM_PORT:=4000}"
: "${CC_LITELLM_DB_PORT:=5443}"
: "${CC_GRAPHITI_PORT:=8000}"
: "${CC_NEO4J_BOLT_PORT:=7687}"
: "${CC_NEO4J_HTTP_PORT:=7474}"
: "${CC_N8N_PORT:=5678}"
: "${CC_CRAWLER_PORT:=8091}"
: "${CC_GRAPHITI_TAG:=1.0.2-anthropic}"
# Enterprise mirrors (work-transition compatibility design, decision 4):
# override to a private mirror when public docker.io/ghcr.io pulls aren't
# reachable. Defaults are today's hardcoded values — no behavior change.
: "${CC_REGISTRY_DOCKERIO:=docker.io}"
: "${CC_REGISTRY_GHCR:=ghcr.io}"
export CC_POD_PREFIX CC_PG_PORT CC_LITELLM_PORT CC_LITELLM_DB_PORT \
       CC_GRAPHITI_PORT CC_NEO4J_BOLT_PORT CC_NEO4J_HTTP_PORT CC_N8N_PORT \
       CC_CRAWLER_PORT CC_GRAPHITI_TAG CC_REGISTRY_DOCKERIO CC_REGISTRY_GHCR

MODE="${1:-all}"
[[ "$MODE" == all || "$MODE" == llm ]] || { echo "usage: $0 [llm]" >&2; exit 1; }

# The LiteLLM half needs the endpoint and the model NAMES; only the core half
# needs the measured dimension, which does not exist yet when `llm` runs.
REQUIRED=(CC_LLM_BASE_URL CC_CHAT_MODEL CC_EMBED_MODEL)
[[ "$MODE" == llm ]] || REQUIRED+=(CC_EMBED_DIM)
for v in "${REQUIRED[@]}"; do
  [[ -n "${!v:-}" ]] || { echo "FATAL: $v is empty in $ENV_FILE" >&2; exit 1; }
done

# Optional split endpoint: embeddings may live on a different server than chat.
# Unset means "same server", so the fallback renders byte-identically to the
# single-endpoint install. ONLY the cc-embedding alias reads these.
: "${CC_EMBED_BASE_URL:=$CC_LLM_BASE_URL}"
export CC_EMBED_BASE_URL

# CC_LLM_API_KEY and CC_EMBED_API_KEY are deliberately ABSENT from this list:
# they reach LiteLLM as podman secrets (make-secrets.sh) and must never be
# rendered into a file that is not 0600.
VARS='$CC_POD_PREFIX $CC_PG_PORT $CC_LITELLM_PORT $CC_LITELLM_DB_PORT $CC_GRAPHITI_PORT $CC_NEO4J_BOLT_PORT $CC_NEO4J_HTTP_PORT $CC_N8N_PORT $CC_CRAWLER_PORT $CC_GRAPHITI_TAG $CC_LLM_BASE_URL $CC_EMBED_BASE_URL $CC_CHAT_MODEL $CC_EMBED_MODEL $CC_EMBED_DIM $CC_REGISTRY_DOCKERIO $CC_REGISTRY_GHCR'

{
  echo "# GENERATED by render.sh from stack-llm.yaml.tmpl — edit the template, not this."
  envsubst "$VARS" <"$HERE/stack-llm.yaml.tmpl"
} >"$HERE/stack-llm.yaml"

# The model catalog seed (register-models.py --policy). Rendered in BOTH modes:
# it is what the llm phase registers right after the proxy answers.
envsubst "$VARS" <"$HERE/models.json.tmpl" >"$HERE/models.json"

if [[ "$MODE" != llm ]]; then
  {
    echo "# GENERATED by render.sh from stack.yaml.tmpl — edit the template, not this."
    echo "apiVersion: v1"
    echo "kind: ConfigMap"
    echo "metadata:"
    echo "  name: ${CC_POD_PREFIX}schema-sql"
    echo "data:"
    echo "  01-schema.sql: |"
    # Four spaces under the block scalar; no substitution of any kind.
    sed 's/^/    /' "$SCHEMA"
    echo "---"
    envsubst "$VARS" <"$HERE/stack.yaml.tmpl"
  } >"$HERE/stack.yaml"

  envsubst "$VARS" <"$HERE/optional-n8n.yaml.tmpl" >"$HERE/optional-n8n.yaml"
  envsubst "$VARS" <"$HERE/optional-crawler.yaml.tmpl" >"$HERE/optional-crawler.yaml"

  echo "wrote stack-llm.yaml, models.json, stack.yaml, optional-n8n.yaml and optional-crawler.yaml"
  echo "  prefix=${CC_POD_PREFIX} chat=${CC_CHAT_MODEL} embed=${CC_EMBED_MODEL}/${CC_EMBED_DIM}d"
  echo "  ports: pg=${CC_PG_PORT} litellm=${CC_LITELLM_PORT} graphiti=${CC_GRAPHITI_PORT} bolt=${CC_NEO4J_BOLT_PORT}"
else
  echo "wrote stack-llm.yaml and models.json (LiteLLM half only — CC_EMBED_DIM not needed yet)"
  echo "  prefix=${CC_POD_PREFIX} chat=${CC_CHAT_MODEL} embed=${CC_EMBED_MODEL} litellm=${CC_LITELLM_PORT}"
fi

# One runnable check: a leaked key in a world-readable file is the failure
# this script's variable list exists to prevent, so prove it every render —
# for BOTH keys, in EVERY file rendered. The LiteLLM half is where the keys
# would land if the variable list ever grew, so it is the one that must be
# checked even in `llm` mode. Length-guarded: a trivial placeholder like `none`
# (common on local servers that enforce no auth) would false-positive on
# ordinary YAML words; any real key clears 8 chars.
leak_check() {  # leak_check <key-value> <label>
  [[ "${#1}" -ge 8 ]] || return 0
  # Pattern via -f <(...) — a /dev/fd path — never as a grep argument, so the
  # key is not visible in `ps` while the check itself runs (printf is a
  # builtin; its args never exec).
  local f
  for f in "$HERE/stack-llm.yaml" "$HERE/models.json" "$HERE/stack.yaml" "$HERE/optional-crawler.yaml"; do
    [[ -f "$f" ]] || continue
    if grep -qF -f <(printf '%s\n' "$1") "$f" 2>/dev/null; then
      echo "FATAL: the $2 was rendered into $(basename "$f") — refusing." >&2
      rm -f "$HERE/stack-llm.yaml" "$HERE/models.json" "$HERE/stack.yaml" "$HERE/optional-crawler.yaml"
      exit 1
    fi
  done
}
leak_check "${CC_LLM_API_KEY:-}"   "LLM API key"
leak_check "${CC_EMBED_API_KEY:-}" "embed API key"
