"""No operator-facing line names a phase to run (v2.58.0, the one-command contract).

The 2026-10-01 design record's D3: `./setup.sh` is THE command — it reads the
ledger and resumes in order — and `./setup.sh <phase>` is a DEVELOPER form the
operator never runs, refused when that phase's prerequisites are not `done`
(D2). D10.4 gives the /setup agent three verbs: change a `.env` key, run
`./setup.sh`, or report with `./setup.sh report`. A FAIL that says `run:
./setup.sh app` hands both of them a command that breaks that contract — the
agent's loop runs it, and the operator gets a refusal, or skips every step in
between. `diagnose` became `report` the same way.

So this walks the installer's message strings — every `pass`/`warn`/`fail`/
`useraction`/`note` (and the other scripts' reporters: verify.sh's `ok`/`bad`/
`skip`, update-run.sh's `write_status`, apply-workflows.sh's `die`, and
`echo`/`printf`) in `deploy/single/*.sh`, `deploy/single/phases/*.sh`
(tests/installer_source.py's `single_scripts`) and
`deploy/n8n/apply-workflows.sh` — and fails on one that names `./setup.sh
<manifest phase>` or `./setup.sh diagnose`. Allowed, because they are
commands rather than a phase to resume: `configure`, `check` (also the
documented loop after editing `.env`), `status`, `report`, `stop`,
`preflight`/`validate`, and `machine --dry-run` (a read-only diff).
Comments, heredocs (the `usage()` text documents the developer form on
purpose) and `logline`/`plan_line` records of what RAN are not messages and are
not scanned.
"""

from __future__ import annotations

import re
from pathlib import Path

from tests.installer_source import ROOT, SINGLE, single_scripts

STEPS = SINGLE / "steps.tsv"
SCANNED = [*single_scripts(), ROOT / "deploy" / "n8n" / "apply-workflows.sh"]

# The reporters, and the few other places a sentence reaches the operator:
# update.sh's `deploy_phase <phase> <the pause sentence>`, a `read -p` prompt,
# and a `*_WHY=` reason a caller later prints (boot.sh's PROC_WHY).
REPORTERS = ("pass", "warn", "fail", "useraction", "note", "ok", "bad", "skip",
             "die", "write_status", "echo", "printf", "deploy_phase", "read",
             r"[A-Z_]*WHY=")


def _phases() -> list[str]:
    seen: list[str] = []
    for line in STEPS.read_text(encoding="utf-8").splitlines():
        if line and not line.startswith("#"):
            p = line.split("\t", 1)[0]
            if p not in seen:
                seen.append(p)
    return seen


# `check` is a manifest phase AND a command (the dry gate the operator runs
# after editing .env); it is the one phase name a message may carry.
FORBIDDEN = [p for p in _phases() if p != "check"] + ["diagnose"]
_HINT = re.compile(
    r"(?<![\w/-])(?:\./)?(?:deploy/single/)?setup\.sh[`'\"]?\s+(" + "|".join(FORBIDDEN) + r")\b"
    r"(?!\s+--dry-run)"
)

# ── the allowlist ───────────────────────────────────────────────────────────
# (file name, a substring of the offending message) for the few places that
# legitimately describe the developer form. Each entry says why. Keep it
# short: an entry here is a message an agent could read as a command.
ALLOWLIST: list[tuple[str, str]] = [
    # The header machine-lib.sh writes INTO the podman machine's generated
    # registries/containers drop-ins, naming what generated them — not a
    # message. It is also file CONTENT the machine phase diffs against what is
    # on the machine, so rewording it would rewrite every existing drop-in.
    ("machine-lib.sh", "# GENERATED by deploy/single/setup.sh machine"),
]

_HEREDOC = re.compile(r"<<-?\s*['\"]?(\w+)['\"]?")
_CALL = re.compile(r"(?:^\s*|[;&|(){]\s*|\bthen\s+|\bdo\s+|\belse\s+|\|\|\s*|&&\s*)(" +
                   "|".join(REPORTERS) + r")(?:\s|(?<==))")


def _unbalanced(text: str) -> bool:
    """True when `text` leaves a double-quoted string open (escapes honoured;
    single quotes outside double ones are literal runs)."""
    dq = sq = False
    i = 0
    while i < len(text):
        c = text[i]
        if c == "\\" and not sq:
            i += 2
            continue
        if c == '"' and not sq:
            dq = not dq
        elif c == "'" and not dq:
            sq = not sq
        i += 1
    return dq


def messages(text: str) -> list[tuple[int, str]]:
    """(line number, statement text) for every reporter call in a script's
    text: comment lines and heredoc bodies skipped, a double-quoted argument
    that runs onto later lines followed (up to eight)."""
    out: list[tuple[int, str]] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        m = _HEREDOC.search(line)
        if m and not line.lstrip().startswith("#"):
            end = m.group(1)
            i += 1
            while i < len(lines) and lines[i].strip() != end:
                i += 1
            i += 1
            continue
        if line.lstrip().startswith("#") or not _CALL.search(line):
            i += 1
            continue
        start, stmt = i, line
        while _unbalanced(stmt) and i + 1 < len(lines) and i - start < 8:
            i += 1
            stmt += "\n" + lines[i]
        out.append((start + 1, stmt))
        i += 1
    return out


def violations(name: str, text: str) -> list[str]:
    found = []
    for lineno, stmt in messages(text):
        for m in _HINT.finditer(stmt):
            if any(name == f and sub in stmt for f, sub in ALLOWLIST):
                continue
            found.append(f"{name}:{lineno}: `{m.group(0)}` in: {stmt.strip()[:160]}")
    return found


def test_no_message_names_a_phase_to_run():
    bad = []
    for path in SCANNED:
        bad += violations(path.name, path.read_text(encoding="utf-8"))
    assert not bad, (
        "an operator-facing message names `./setup.sh <phase>` (or `diagnose`) as a command. "
        "The operator runs ONE command — `./setup.sh`, which resumes in order (say \"it resumes "
        "at <phase>\" where that helps) — and `./setup.sh report` instead of diagnose:\n  "
        + "\n  ".join(bad)
    )


def test_the_scan_covers_the_installer_and_the_n8n_script():
    names = {p.name for p in SCANNED}
    assert {"setup.sh", "update.sh", "update-run.sh", "verify.sh", "resolve-images.sh",
            "make-secrets.sh", "apply-workflows.sh", "stack.sh", "llm.sh"} <= names, names
    # And it actually finds messages in them — a parser that matched nothing
    # would pass the guard above forever.
    stack = SINGLE / "phases" / "stack.sh"
    assert len(messages(stack.read_text(encoding="utf-8"))) >= 10


def test_the_guard_catches_a_planted_violation():
    planted = "\n".join([
        'phase_x() {',
        '  fail "venv" ".venv missing — run: ./setup.sh app"',
        '  useraction "llm-models" "fill the catalog, then re-run: ./setup.sh llm"',
        '  note "  need longer:  CC_PROBE_TIMEOUT=900 ./setup.sh llm"',
        '  warn "x" "a long message that wraps',
        '     onto the next line and says re-run ./setup.sh demo"',
        '  [[ -n "$x" ]] || fail "x" "proxy never answered — run: ./setup.sh diagnose"',
        '  write_status failed "rollback" "then: ./update.sh rollback && ./setup.sh boot"',
        '}',
    ])
    found = violations("planted.sh", planted)
    for hint in ("setup.sh app", "setup.sh llm", "setup.sh demo", "setup.sh diagnose",
                 "setup.sh boot"):
        assert any(hint in f for f in found), (hint, found)
    assert len(found) == 6, found


def test_the_guard_leaves_commands_comments_and_usage_alone():
    clean = "\n".join([
        '# a comment may say: run ./setup.sh app',
        'usage() {',
        '  cat >&2 <<USAGE',
        '       ./setup.sh <phase>   # developer form: ./setup.sh app',
        'USAGE',
        '}',
        'f() {',
        '  fail "x" "requires app/install, which is pending — run ./setup.sh (it resumes in order)"',
        '  warn "y" "fix the key in .env, then run: ./setup.sh check"',
        '  pass "z" "./setup.sh machine --dry-run reports the diff"',
        '  fail "w" "git not found (./setup.sh preflight)"',
        '  useraction "v" "run ./setup.sh report and hand over the file; ./setup.sh status shows it"',
        '  logline "run end: ./setup.sh machine -> exit 0"',
        '  "$HERE/setup.sh" boot',
        '}',
    ])
    assert violations("clean.sh", clean) == []
