"""No operator-facing line names a phase to run (v2.58.0, the one-command contract).

The 2026-10-01 design record's D3: `./setup.sh` is THE command — it reads the
ledger and resumes in order — and `./setup.sh <phase>` is a DEVELOPER form the
operator never runs, refused when that phase's prerequisites are not `done`
(D2). D10.4 gives the /setup agent three verbs: change a `.env` key, run
`./setup.sh`, or report with `./setup.sh report`. A FAIL that says `run:
./setup.sh app` hands both of them a command that breaks that contract — the
agent's loop runs it, and the operator gets a refusal, or skips every step in
between. `diagnose` became `report` the same way.

So this walks the installer's message strings — every `pass`/`warn`/`fail`/
`useraction`/`note` (and the other scripts' reporters: verify.sh's `ok`/`bad`/
`skip`, update-run.sh's `write_status`, apply-workflows.sh's `die`, and
`echo`/`printf`) in `deploy/single/*.sh`, `deploy/single/phases/*.sh`
(tests/installer_source.py's `single_scripts`) and
`deploy/n8n/apply-workflows.sh` — and fails on one that names `./setup.sh
<manifest phase>` or `./setup.sh diagnose`. Allowed, because they are
commands rather than a phase to resume: `configure`, `check` (also the
documented loop after editing `.env`), `status`, `report`, `stop` and
`preflight`/`validate`. Two holes closed after the first laptop acceptance
run (P5, F1) found a line in each: `machine --dry-run` is the developer's
read-only diff and no longer passes as a command to hand the operator (a
message may say what the machine phase WILL write, never which command shows
it), and a `next:` hand-off names `./setup.sh` alone — `configure` ended
`next: ./setup.sh check`, where the checklist's next move is the one command,
which runs the check first.
Comments, heredocs (the `usage()` text documents the developer form on
purpose) and `logline`/`plan_line` records of what RAN are not messages and are
not scanned.

The same walk carries a second guard (P5, F14): no message tells the reader to
EDIT a tracked file — `compose.yaml`, `images.txt`, a manifest, "the litellm
service by hand" — because D10's tree-pristine check refuses the result. A
message names the `.env` key, or `./setup.sh report` for a finding.
"""

from __future__ import annotations

import re
from pathlib import Path

from tests.installer_source import ROOT, SINGLE, single_scripts

STEPS = SINGLE / "steps.tsv"
SCANNED = [*single_scripts(), ROOT / "deploy" / "n8n" / "apply-workflows.sh"]

# The reporters, and the few other places a sentence reaches the operator:
# update.sh's `deploy_phase <phase> <the pause sentence>`, a `read -p` prompt,
# and a `*_WHY=` reason a caller later prints (boot.sh's PROC_WHY).
REPORTERS = ("pass", "warn", "fail", "useraction", "note", "ok", "bad", "skip",
             "die", "write_status", "echo", "printf", "deploy_phase", "read",
             r"[A-Z_]*WHY=")


def _phases() -> list[str]:
    seen: list[str] = []
    for line in STEPS.read_text(encoding="utf-8").splitlines():
        if line and not line.startswith("#"):
            p = line.split("\t", 1)[0]
            if p not in seen:
                seen.append(p)
    return seen


# `check` is a manifest phase AND a command (the dry gate the operator runs
# after editing .env); it is the one phase name a message may carry.
FORBIDDEN = [p for p in _phases() if p != "check"] + ["diagnose"]
_HINT = re.compile(
    r"(?<![\w/-])(?:\./)?(?:deploy/single/)?setup\.sh[`'\"]?\s+(" + "|".join(FORBIDDEN) + r")\b"
)
# A hand-off to the operator's NEXT move names the one command and nothing
# after it — `check` included, though it is otherwise allowed (see above).
_NEXT = re.compile(
    r"\bnext:\s*(?:\./)?(?:deploy/single/)?setup\.sh[`'\"]?\s+(" + "|".join(_phases()) + r")\b"
)

# ── the allowlist ───────────────────────────────────────────────────────────
# (file name, a substring of the offending message) for the few places that
# legitimately describe the developer form. Each entry says why. Keep it
# short: an entry here is a message an agent could read as a command.
ALLOWLIST: list[tuple[str, str]] = [
    # The header machine-lib.sh writes INTO the podman machine's generated
    # registries/containers drop-ins, naming what generated them — not a
    # message. It is also file CONTENT the machine phase diffs against what is
    # on the machine, so rewording it would rewrite every existing drop-in.
    ("machine-lib.sh", "# GENERATED by deploy/single/setup.sh machine"),
    # The same generated header's second line, naming the developer form that
    # re-renders it — drop-in CONTENT for the same reason as the line above.
    ("machine-lib.sh", "Re-render with: ./deploy/single/setup.sh machine --dry-run"),
]

_HEREDOC = re.compile(r"<<-?\s*['\"]?(\w+)['\"]?")
_CALL = re.compile(r"(?:^\s*|[;&|(){]\s*|\bthen\s+|\bdo\s+|\belse\s+|\|\|\s*|&&\s*)(" +
                   "|".join(REPORTERS) + r")(?:\s|(?<==))")


def _unbalanced(text: str) -> bool:
    """True when `text` leaves a double-quoted string open (escapes honoured;
    single quotes outside double ones are literal runs)."""
    dq = sq = False
    i = 0
    while i < len(text):
        c = text[i]
        if c == "\\" and not sq:
            i += 2
            continue
        if c == '"' and not sq:
            dq = not dq
        elif c == "'" and not dq:
            sq = not sq
        i += 1
    return dq


def messages(text: str) -> list[tuple[int, str]]:
    """(line number, statement text) for every reporter call in a script's
    text: comment lines and heredoc bodies skipped, a double-quoted argument
    that runs onto later lines followed (up to eight)."""
    out: list[tuple[int, str]] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        m = _HEREDOC.search(line)
        if m and not line.lstrip().startswith("#"):
            end = m.group(1)
            i += 1
            while i < len(lines) and lines[i].strip() != end:
                i += 1
            i += 1
            continue
        if line.lstrip().startswith("#") or not _CALL.search(line):
            i += 1
            continue
        start, stmt = i, line
        while _unbalanced(stmt) and i + 1 < len(lines) and i - start < 8:
            i += 1
            stmt += "\n" + lines[i]
        out.append((start + 1, stmt))
        i += 1
    return out


def violations(name: str, text: str) -> list[str]:
    found = []
    for lineno, stmt in messages(text):
        for m in [*_HINT.finditer(stmt), *_NEXT.finditer(stmt)]:
            if any(name == f and sub in stmt for f, sub in ALLOWLIST):
                continue
            found.append(f"{name}:{lineno}: `{m.group(0)}` in: {stmt.strip()[:160]}")
    return found


def test_no_message_names_a_phase_to_run():
    bad = []
    for path in SCANNED:
        bad += violations(path.name, path.read_text(encoding="utf-8"))
    assert not bad, (
        "an operator-facing message names `./setup.sh <phase>` (or `diagnose`) as a command. "
        "The operator runs ONE command — `./setup.sh`, which resumes in order (say \"it resumes "
        "at <phase>\" where that helps) — and `./setup.sh report` instead of diagnose:\n  "
        + "\n  ".join(bad)
    )


def test_the_scan_covers_the_installer_and_the_n8n_script():
    names = {p.name for p in SCANNED}
    assert {"setup.sh", "update.sh", "update-run.sh", "verify.sh", "resolve-images.sh",
            "make-secrets.sh", "apply-workflows.sh", "stack.sh", "llm.sh"} <= names, names
    # And it actually finds messages in them — a parser that matched nothing
    # would pass the guard above forever.
    stack = SINGLE / "phases" / "stack.sh"
    assert len(messages(stack.read_text(encoding="utf-8"))) >= 10


def test_the_guard_catches_a_planted_violation():
    planted = "\n".join([
        'phase_x() {',
        '  fail "venv" ".venv missing — run: ./setup.sh app"',
        '  useraction "llm-models" "fill the catalog, then re-run: ./setup.sh llm"',
        '  note "  need longer:  CC_PROBE_TIMEOUT=900 ./setup.sh llm"',
        '  warn "x" "a long message that wraps',
        '     onto the next line and says re-run ./setup.sh demo"',
        '  [[ -n "$x" ]] || fail "x" "proxy never answered — run: ./setup.sh diagnose"',
        '  write_status failed "rollback" "then: ./update.sh rollback && ./setup.sh boot"',
        # The two P5 found (F1): a dry-run command handed to the operator, and
        # a `next:` that names check where the one command is the move.
        '  pass "z" "./setup.sh machine --dry-run reports the diff"',
        '  note "next: ./setup.sh check"',
        '}',
    ])
    found = violations("planted.sh", planted)
    for hint in ("setup.sh app", "setup.sh llm", "setup.sh demo", "setup.sh diagnose",
                 "setup.sh boot", "setup.sh machine", "next: ./setup.sh check"):
        assert any(hint in f for f in found), (hint, found)
    assert len(found) == 8, found


def test_the_guard_leaves_commands_comments_and_usage_alone():
    clean = "\n".join([
        '# a comment may say: run ./setup.sh app',
        'usage() {',
        '  cat >&2 <<USAGE',
        '       ./setup.sh <phase>   # developer form: ./setup.sh app',
        'USAGE',
        '}',
        'f() {',
        '  fail "x" "requires app/install, which is pending — run ./setup.sh (it resumes in order)"',
        '  warn "y" "fix the key in .env, then run: ./setup.sh check"',
        '  pass "z" "the machine phase owns the drop-in, and prints its diff before it writes"',
        '  note "next: ./setup.sh   (it runs the dry check first, then installs)"',
        '  fail "w" "git not found (./setup.sh preflight)"',
        '  useraction "v" "run ./setup.sh report and hand over the file; ./setup.sh status shows it"',
        '  logline "run end: ./setup.sh machine -> exit 0"',
        '  "$HERE/setup.sh" boot',
        '}',
    ])
    assert violations("clean.sh", clean) == []


# ── no message tells the reader to edit a tracked file (P5, F14) ───────────
# The 2026-10-01 design record's D10: a deployment carries no local patches —
# `check/tree-pristine` refuses a tree that differs from its release, and the
# agent's hook denies the edit. So a message that says "add HTTP(S)_PROXY to
# the litellm service by hand" (the llm pause's stderr said exactly that, the
# first laptop run found) sends the reader into a refusal, the agent off its
# contract, and the change nowhere it can travel back from. The move a message
# may name is an `.env` key, or `./setup.sh report` for a finding.
#
# What counts as a tracked file: the release CONTENT under deploy/ that a
# reader could be told to change — compose files, images.txt, the manifests,
# configs, Dockerfiles — plus the root's pyproject.toml, requirements.lock and
# VERSION. Scripts are left out on purpose: messages name them as commands to
# RUN, constantly, and "edit setup.sh" is not a sentence anyone writes.

_CONTENT_SUFFIXES = (".yaml", ".yml", ".txt", ".tsv", ".json", ".conf", ".toml", ".lock")


def _tracked_content_names() -> set[str]:
    names = {"VERSION", "pyproject.toml", "requirements.lock"}
    for p in (ROOT / "deploy").rglob("*"):
        if not p.is_file() or p.name.startswith(".env"):
            continue
        if p.suffix in _CONTENT_SUFFIXES or p.name.startswith("Dockerfile"):
            names.add(p.name)
    return names


_EDIT_VERBS = r"(?:edit|modify|patch|change|add|append|insert|uncomment|bump|set|put|write|tweak|hand-edit)"
_EDIT_FILE = re.compile(
    r"\b" + _EDIT_VERBS + r"\b[^.;\n]{0,80}?(?<![\w.-])(?:[\w./-]*/)?("
    + "|".join(sorted((re.escape(n) for n in _tracked_content_names()), key=len, reverse=True))
    + r")(?![\w.-])",
    re.I,
)
# ...and the shapes that name no file at all but mean one: a compose SERVICE
# or a container's definition, or anything to be done "by hand" to one.
_EDIT_SERVICE = re.compile(
    r"\b(?:add|edit|patch|modify|change|append|insert)\b[^.;\n]{0,80}\bto the [\w-]+ (?:service|container)\b",
    re.I,
)
_EDIT_BY_HAND = re.compile(
    r"\b(?:add|edit|patch|modify|change|append|insert)\b[^.;\n]{0,80}\bby hand\b", re.I,
)


def tree_edit_violations(name: str, text: str) -> list[str]:
    found = []
    for lineno, stmt in messages(text):
        for rx in (_EDIT_FILE, _EDIT_SERVICE, _EDIT_BY_HAND):
            for m in rx.finditer(stmt):
                found.append(f"{name}:{lineno}: `{m.group(0)}` in: {stmt.strip()[:160]}")
    return found


def test_no_message_tells_the_reader_to_edit_a_tracked_file():
    bad = []
    for path in SCANNED:
        bad += tree_edit_violations(path.name, path.read_text(encoding="utf-8"))
    assert not bad, (
        "an operator-facing message tells the reader to change a TRACKED file. A deployment "
        "carries no local patches (2026-10-01 design record, D10): the tree-pristine check "
        "refuses it. Name the .env key that does it — or, where none exists, say so and point "
        "at ./setup.sh report as a finding:\n  " + "\n  ".join(bad)
    )


def test_the_tree_edit_guard_catches_a_planted_violation():
    planted = "\n".join([
        'f() {',
        # The llm pause's own lines, as the first laptop run read them (F14).
        '  note "  item in the design record: add HTTP(S)_PROXY to the litellm service"',
        '  note "  by hand if you need it."',
        '  fail "x" "the tag is wrong — edit deploy/single/images.txt and re-run ./setup.sh"',
        '  useraction "y" "change compose.yaml so the port is free, then re-run ./setup.sh"',
        '  warn "z" "patch the healthcheck by hand"',
        '}',
    ])
    found = tree_edit_violations("planted.sh", planted)
    for hint in ("litellm service", "images.txt", "compose.yaml", "by hand"):
        assert any(hint in f for f in found), (hint, found)


def test_the_tree_edit_guard_leaves_env_keys_commands_and_findings_alone():
    clean = "\n".join([
        'f() {',
        '  fail "x" "fix or unset CC_IMG_REDIS in .env, then re-run: ./setup.sh"',
        '  note "  Do not add one to a tracked file: the install refuses a tree that differs"',
        '  useraction "y" "set it in .env or run ./setup.sh configure in a terminal"',
        '  warn "z" "podman-compose must be 1.6.0 or newer; check it by hand"',
        '  fail "w" "images.txt locks a digest the registry does not serve — do not install it"',
        '  pass "v" "wrote the drop-in from CC_PROXY (deploy/single/compose.yaml is untouched)"',
        '}',
    ])
    assert tree_edit_violations("clean.sh", clean) == []
